### ISSUE TITLE
🎃[Provider Request]: Implement DuckDB as an Offline Store

### ISSUE THREAD

**Issue by shabbyjoon** [featureform/featureform#1070]
### Description

[DuckDB](https://duckdb.org/) is an in-process SQL OLAP database management system. Implement DuckDB as an Offline Store

### Desired Behavior

The ability to register DuckDB as an [Offline Store Provider](https://docs.featureform.com/providers/offline-store) in Featureform so that it can store primary data and function as a transformation engine.

### Benefits

With DuckDB provider support, users can manage and version their transformations, features, and training sets with Featureform while leveraging DuckDB.

### Possible Implementation

It should implement the offline store interface https://github.com/featureform/featureform/blob/main/provider/offline.go#L253

Look at https://github.com/featureform/featureform/blob/main/provider/postgres.go for inspiration

**Comment by neelshah2409** [comment]
Hey @shabbyjoon I would like to work on it

**Comment by error9098x** [comment]
@shabbyjoon  can I try this one :)

**Comment by error9098x** [comment]
@neelshah2409 Hey, if you are busy doing other contributions in open source, would you like me to handle this particular Issue, I think I can contribute in this the most. It will be really great, if you could will be take this one. Thanks

**Comment by neelshah2409** [comment]
@error9098x I am already working on it and would complete it in a day

**Comment by shabbyjoon** [comment]
Hi @error9098x! We added a couple more Hacktoberfest tickets for technical contributions, you can check them out here: https://github.com/featureform/featureform/issues

Thanks again for your support! :)
