### ISSUE TITLE
[Bug]: Copyright year in footer required

### ISSUE THREAD

**Issue by tmsagarofficial** [featureform/featureform#1092]
### Expected Behavior

The copyright year should match with the current year i.e 2023

### Actual Behavior

Its showing 2022

### Steps To Reproduce

- Go to https://www.featureform.com
- Scroll till the bottom
- See the footer
<img width="467" alt="Screenshot 2023-10-18 061218" src="https://github.com/featureform/featureform/assets/110724849/6084648a-ff62-4005-83d3-01e39c576552">
its 2022 😅 

### What mode are you running Featureform in?

Hosted

### What version of Python are you running?

3.7

### Featureform Python Package Version

NA

### Featureform Helm Chart Version

NA

### Kubernetes Version

NA

**Comment by sdreyer** [comment]
Hey @tmsagarofficial , that part of the website is not included within this code base, so unfortunately there's no work to be done here.

**Comment by tmsagarofficial** [comment]
Okay Not a problem.

But if u can point me to the correct repo I will be more than happy to help. @sdreyer
