### ISSUE TITLE
Dashboard Preview: Show only like X records

### ISSUE THREAD

**Issue by ahmadnazeri** [featureform/featureform#1099]
Currently, the dashboard shows all the data when you click on Preview. It might be a good idea to limit it to like 100 or X records.
```[tasklist]
### Tasks
- [x] Identify the right number of records to display on the dashboard
- [x] Implement the limit
- [x] PR Merged
```

**Comment by sdreyer** [comment]
This is currently limited to 150 records and 15 rows
