### ISSUE TITLE
Databricks Config Validation

### ISSUE THREAD

**Issue by sdreyer** [featureform/featureform#1143]
# Goal
We want to validate that the Cluster ID and Token are in the proper format to avoid confusion with users. 

# Requirements
When creating Databricks credentials in the client, we should validate inputs on object creation.
```
ff.DatabricksCredentials(
   host=<url>, 
   cluster_id=<cluster_id>, 
   token=<token>
) 
```

cluster_id should follow the format: xxx-xxxxxx-xxxxxxxx
and token should always start with dapi ex: dapixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-x

Where 'x' is alphanumeric.

## Testing
Unit tests should be added in the client/tests directory using pytest and should cover:
- Valid tokens and IDs
- Empty tokens and IDs
- Invalid characters
- Incorrectly formatted tokens and IDs

**Comment by ihkap11** [comment]
I can take this up
