### ISSUE TITLE
Persisting embeddings in local mode

### ISSUE THREAD

**Issue by josephrocca** [featureform/featureform#158]
I'm using EmbeddingHub in local mode like this:
```python
import embeddinghub as eh
hub = eh.connect(eh.LocalConfig("/path/to/data"))
term_space = hub.create_space("terms", dims=768)

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2')

terms = ["apple", "orange", "potato", "chicken"]
embeddings = {}
for t in terms:
  embeddings[t] = model.encode(t)

term_space.multiset(embeddings)

hub.save()
```

But `hub.save()` outputs "SAVE NOT IMPLEMENTED YET". On [this page](https://docs.featureform.com/guide/local_mode) it says `hub.save()` is needed to persist data in local mode.

So given that `hub.save()` isn't yet implemented, I'm just wondering if there is currently any way to persist embeddings in local mode?

Thanks for your work on this project!

**Comment by simba-git** [comment]
There's currently no way to persist embeddings in local mode, we'll work on getting it in!
