### ISSUE TITLE
cli commands `list` and `get` don't work in secure non-local mode

### ISSUE THREAD

**Issue by ekorman** [featureform/featureform#351]
Doing a command such as
```shell
featureform list sources --host <HOST_NAME> --cert tls.crt
```
results in the error `ValueError: Cannot be local and have a host`. This is because it looks like `insecure` `False` forces local mode:

https://github.com/featureform/featureform/blob/main/client/src/featureform/cli.py#L132

Similar logic is in the `get` command. The `apply` command however does work and has different logic for creating the `ResourceClient`:
https://github.com/featureform/featureform/blob/main/client/src/featureform/cli.py#L172

is there a reason that the `get` and `list` commands don't create the `ResourceClient` this way?

**Comment by sdreyer** [comment]
Fix included in Python package v1.1.10
