### ISSUE TITLE
[Bug]: Broken image in "Software" column in dashboard at Home > Providers

### ISSUE THREAD

**Issue by epps** [featureform/featureform#597]
### Expected Behavior

The image should render whatever represents the value for "Software" in local mode.

### Actual Behavior

The image element is broken given there's no value for the `src` attribute.

It appears that [line 151 in ResourceListView.js](https://github.com/featureform/featureform/blob/main/dashboard/src/components/resource-list/ResourceListView.js#L151)  indexes into the `providerLogos` object with the key `LOCALMODE`, which doesn't exist (see [line 115 in Resources.js](https://github.com/featureform/featureform/blob/main/dashboard/src/api/resources/Resources.js#L115). This results the value `undefined` for the `src` attribute.

### Steps To Reproduce

* Complete Steps 1-3 in [Quickstart (Local}](https://docs.featureform.com/quickstart-local) and run `featureform dash`
* Visit `http://localhost:3000/providers`
* Observe the broken image under the "Software" column.
![Screen Shot 2023-01-20 at 1 29 32 PM](https://user-images.githubusercontent.com/10430775/213830210-66e647ab-79dd-442f-aa63-476df296f291.png)

### What mode are you running Featureform in?

Local

### What version of Python are you running?

3.8

### Featureform Python Package Version

1.4.4

**Comment by sdreyer** [comment]
Resolved in https://github.com/featureform/featureform/pull/601
