### ISSUE TITLE
[Bug]: Acessing localhost:7878 cannot open

### ISSUE THREAD

**Issue by gustavomr** [featureform/featureform#724]
### Expected Behavior

Open web page and mantain communication between docker and interface

### Actual Behavior

time="2023-04-06T18:45:08Z" level=info msg="[core] [Server #7] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET /favicon.ico HTTP/1.\\\"\"" system=system

### Steps To Reproduce

Follow the tutorial from featureform using Docker

### What mode are you running Featureform in?

Local

### What version of Python are you running?

3.10

### Featureform Python Package Version

1.7.2

**Comment by sdreyer** [comment]
Hey @gustavomr , it sounds like be trying to access to dashboard at localhost:7878, could you trying accessing it at localhost:80?

**Comment by gustavomr** [comment]
You are right! Now I can access! Thanks
