### ISSUE TITLE
Configure nginx to use a single config file and update any  jobs.

### ISSUE THREAD

**Issue by anthonylasso** [featureform/featureform#763]
Currently the the application has 2 `nginx.conf` files between the `root` directory and the `dashboard` directory. 

Ideally we should only use 1, and copy it as needed in the build scripts. 

Remove 1 of the config files, and update any jobs as necessary.

**Comment by RedLeader16** [comment]
A complicating factor is that the `/data` route uses a different proxy value. If there is no way around this, then we'll have to keep 2 files.

**Comment by anthonylasso** [comment]
Closing the issue and keeping both files since the dashboard needs the ability to build independently as well.
