### ISSUE TITLE
Display all available SourceVariant data

### ISSUE THREAD

**Issue by RedLeader16** [featureform/featureform#822]
Currently the Source view is limited in the information it displays to the user. The `metadata.proto` type defines properties that are not displayed to the users. 

The missing properties (in the view) are: 

-definition: transformation / primaryData
-table
-last_updated
-schedule
-tags
-properties*

*a generic map object of <string, string>. This list of propertyName:values should be displayed to the user in a concise format. 

Full Source Variant definition:
```
message SourceVariant {
    string name = 1;
    string variant = 2;
    oneof definition {
        Transformation transformation = 14;
        PrimaryData primaryData = 15;
    }
    string owner = 4;
    string description = 5;
    string provider = 6;
    google.protobuf.Timestamp created = 7;
    ResourceStatus status = 8;
    string table = 9;
    repeated NameVariant trainingsets = 10;
    repeated NameVariant features = 11;
    repeated NameVariant labels = 12;
    google.protobuf.Timestamp last_updated = 13;
    string schedule = 16;
    Tags tags = 17;
    Properties properties = 18;
}
```

Current View:
<img width="1204" alt="image" src="https://github.com/featureform/featureform/assets/34227093/c66c22e2-f289-4acb-a0ed-5cf44b1e1e7a">

Proto -> Element Mapping:
| Proto Prop | Element Type |
|--------|--------|
| name | label |
| variant | label |
| definition.transformation | textarea |
| definition.primaryData | textarea |
| owner | label | 
| description | textarea | 
| provider | label | 
| created | datefield | 
| status | label | 
| table | ?? |  
| trainingsets | table |  
| features | table |  
| labels | table |  
| last_updated | datefield |  
| schedule | label |  
| tags | table |  
| properties | table/textarea |

**Comment by sdreyer** [comment]
I believe last_updated is the timstamp unless
