### ISSUE TITLE
Missing code in sdk/python when installing local build

### ISSUE THREAD

**Issue by SanRehmo** [featureform/featureform#85]
Found this issue when I tried to import the Python package after installing a local build via `pip install -e .`

There seems to be some code missing under `sdk/python`:

```python
>>> import embeddinghub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/code/embeddinghub/sdk/python/embeddinghub.py", line 19, in <module>
    from sdk.python import embedding_store_pb2_grpc
ImportError: cannot import name 'embedding_store_pb2_grpc' from 'sdk.python' (/Users/user/code/embeddinghub/sdk/python/__init__.py)
```

The file structure currently looks like this:
<img width="402" alt="Bildschirmfoto 2021-10-27 um 12 47 46" src="https://user-images.githubusercontent.com/21010788/139051697-49f6d275-e65d-4f9a-8059-cab5f0e81c78.png">

**Comment by simba-git** [comment]
Hi there! The way to build the client uses Bazelisk to generate the necessary files via our .proto files. Gonna create an issue to make it easy to build and install via pip locally
