### ISSUE TITLE
[Feature Request]: What's the software to fraw your virtual_arch.png

### ISSUE THREAD

**Issue by hudengjunai** [featureform/featureform#981]
### Description

what's software do you use to draw the virt_arch.png illustrate the featuresture pipeline

### Current Behavior

I use draw.io, I'm wandering what tools do you use.

### Desired Behavior

the software name and download url

### Benefits

pure a skill obtained.

**Comment by hudengjunai** [comment]
https://raw.githubusercontent.com/featureform/featureform/main/assets/virtual_arch.png

**Comment by ahmadnazeri** [comment]
@hudengjunai, this architecture diagram was done using Adobe Illustrator by a designer.
